[project]
target-path = "bin"
results-path = "results"

[osc]
default-branch = "openEuler-22.03-LTS-SP1-release"
openEuler = "https://gitee.com/src-openeuler/"

[osc-project-build-folder]
curl = "build-full"

[rust]
version = "nightly-2021-11-22"

[c2rust]
version = "v0.16.0"
repo = "https://gitee.com/mirrors/C2Rust.git"
