[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "safer-c2rust"
requires-python = ">=3.8"
description = ""
version = "1.0.0"
dependencies = [
    "click",
    "loguru",
    "plumbum",
    "toml",
    "scan-build"
]